# Generated by Django 5.1.2 on 2024-10-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=200)),
                ('short_url', models.CharField(max_length=100, unique=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
